### PR TITLE
fix: First start ui being blank on windows

### LINKED ISSUE #1025: [Bug] App just not opening
### Discord Account

mazeymoos0022

### Operating System

Windows 11

### Linux Only ~ Desktop Environment

_No response_

### Package Type

Setup EXE (Installer)

### What happens when the bug or crash occurs?

Title explains it all, I click the app, not opening. Just get this white box. Using version 1.5.4 (latest). Tried reinstalling and also restarting my machine... Still no luck. Been working fine on v1.5.3
image

### What is the expected behaviour?

Vesktop/Discord should open

### How do you recreate this bug or crash?

1) Open the app... That's all I did... 

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

### PR DESCRIPTION
**Pull request by Covkie**
fixes #1025

### CODE REVIEW

File: src/main/firstLaunch.ts [hunk 1]
```diff
@@ -28,6 +28,7 @@ interface Data {
 export function createFirstLaunchTour() {
     const win = new BrowserWindow({
         ...SplashProps,
+        transparent: false,
```
Comment (Vendicated) [inline src/main/firstLaunch.ts:31]: just remove it from SplashProps instead
